---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-production
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vault
      version: 0.19.0
  interval: 30s
  targetNamespace: production
  values:
#    image:
#     tag: 0.18.0
    ingress:
      host: production.vault.192.168.72.104.nip.io

